services:
  db:
    image: postgres:16
    container_name: shared_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  polytech:
    profiles: [app]
    build: ./polytech
    container_name: polytech_app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - erasmumu
      - mi8
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=school
      - ERASMUMU_URL=http://erasmumu:8081
      - MI8_URL=http://mi8:8082

  erasmumu:
    profiles: [app]
    build: ./erasmumu
    container_name: erasmumu_app
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=school

  mi8:
    profiles: [app]
    build: ./mi8
    container_name: mi8_app
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=school

volumes:
  postgres_data:
